export const pricing = [
  {
    text: "Basic Plan",
    color: "white",
    price: 500000,
    subtitle: "20 Soft Edited Pictures",
    features: [
      { icon: "yes", text: "1 Photographer" },
      { icon: "yes", text: "Duration: 1 hour" },
      { icon: "yes", text: "Locations: 1" },
      { icon: "yes", text: "Pictures: 20 Soft Edited File" },
      { icon: "yes", text: "File shared via Google Drive" },
    ],
    bookType: "basic",
  },
  {
    text: "Standard Plan",
    color: "black",
    price: 800000,
    subtitle: "All files includes RAW + 35 Edited Pictures",
    tag: "Popular Choice",
    features: [
      { icon: "yes", text: "2 Photographer" },
      { icon: "yes", text: "Duration: 2 hours" },
      { icon: "yes", text: "Locations: Up to 2" },
      { icon: "yes", text: "Pictures: 35 Edited File" },
      { icon: "yes", text: "All files in JPG format" },
      { icon: "yes", text: "Free pose request" },
      { icon: "yes", text: "File shared via Google Drive" },
    ],
    bookType: "standard",
  },
  {
    text: "Premium Plan",
    color: "white",
    price: 1200000,
    subtitle: "Includes RAW + 100 Edited Pictures",
    features: [
      { icon: "yes", text: "1 Photographer" },
      { icon: "yes", text: "1 Videographer" },
      { icon: "yes", text: "Duration: 3 hours" },
      { icon: "yes", text: "Pictures: Unlimited" },
      { icon: "yes", text: "All files in JPG format" },
      { icon: "yes", text: "Free pose request" },
      { icon: "yes", text: "Pictures: 50 Edited File" },
      { icon: "yes", text: "Locations: Customizable / Negotiable" },
    ],
    bookType: "premium",
  },
];
